inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Rails/HelperInstanceVariable:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - require
    - require_relative
    - require_dependency
    - yield
    - raise
    - puts
  Exclude:
  - "/**/Gemfile"
